### ISSUE TITLE
[GUIDE] Installation and usage guide for musicians

### ISSUE THREAD

**Issue by Zokhoi** [kuielab/mdx-net-submission#10]
# The following guide is no longer needed and is out of date since [the repository's README](https://github.com/kuielab/mdx-net-submission/tree/master#readme) has been updated.

This guide is written because the README is not very detailed as to how to install and use this code base. I managed to figure things out on my own but a guide would be nice in my opinion.

Also the code look like it's being refractorized, so this guide serves only for the original state of the code.

### Warning: The repository supports Linux and does not support Windows (MacOS untested).

Setup [git-lfs](https://git-lfs.github.com/) first. You will need it to download the models inside this repository.
You'd also need [conda](https://docs.conda.io/en/latest/miniconda.html).

After all those are installed, clone the [`leaderboard_B`](https://github.com/kuielab/mdx-net-submission/tree/leaderboard_B) branch:

```bash
git clone -b leaderboard_B https://github.com/kuielab/mdx-net-submission.git
```

In the cloned repository directory, do

```bash
conda env create -f environment.yml -n mdx-submit
conda activate mdx-submit
pip install -r requirements.txt
pip install demucs==2.0.3
python download_demucs.py
```

Onnxruntime currently does not have a version for python 3.10, so conda and pip will fail to install it. If you encounter this problem, just do

```bash
conda install python=3.9
pip install onnxruntime
```

And you're good.

Also, every time when you open a new terminal, conda will default to environment `base`.
Just do 

```bash
conda activate mdx-submit
```

to go back into the environment you have installed MDX's dependencies in.

## Usage

To go through all these hoops to install this AI demixer, you are probably looking for the best vocal separation result (for other stems you'd be better off with [demucs v3](https://github.com/facebookresearch/demucs)). Here's an [even better vocal model trained by UVR team](https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/MDX-Net-B) to replace `./onnx/vocals.onnx` with.

After successful installation, you can put the songs you wish to separate as `./data/test/SONGNAME/mixture.wav`, and run either `run.sh` or

```bash
python predict_blend.py
```

After the separation completes, the results will be saved in `./data/results/baseline/SONGNAME/`.

**Comment by ws-choi** [comment]
Hi @Zokhoi , Thank you for writing this valuable document.
I can revise README.md directly, but I think it would be better if you make a pull request to this repository, as an official contributor (if you want).

**Comment by Zokhoi** [comment]
Thanks for the reply. As it seems that you are busy with another project at the moment, and that the different branches need to be updated separately, I would like to have a collaborator role for potentially less work.

**Comment by Zokhoi** [comment]
Closing this as the README of the branches have been updated.
