### ISSUE TITLE
Invoke-WebRequest Error

### ISSUE THREAD

**Issue by ProgressiveProgression** [kuielab/mdx-net-submission#16]
Hi. I am using Conda and when I use **Invoke-WebRequest** command, I get an error that 'Invoke-WebRequest' is not recognized as an internal or external command. The version of PowerShell is 5.1 and I use Win10. Thank you in advance.

**Comment by Zokhoi** [comment]
Hi, can you provide the full console output with error log such that it would be easier for others to debug the error?

**Comment by ProgressiveProgression** [comment]
Hi. It seems that I found a workaround for this particular problem: instead of using Anaconda Shell I was able to use the xommand in the standard Windows Powershell. Before that I had to move to my mdx-net directory. You can see it on screenshot down here
![mdx-net](https://user-images.githubusercontent.com/94316275/172645582-83347257-55fa-4dc0-826a-798d4588df88.JPG)
.

**Comment by Zokhoi** [comment]
Seems like you were using anaconda cmd prompt instead of powershell prompt where the error happened, which is normal. Please use the anaconda powershell prompt for the commands in the readme guide.

**Comment by ProgressiveProgression** [comment]
Ok, thank you. I am a novice at this, so I did not realise that Anaconda has it's  own shell. So, this request can be closed.

**Comment by Zokhoi** [comment]
No, the anaconda prompts add some hooks to the existing prompts on your computer for its functionality, and as windows have cmd and powershell prompts, there are anaconda cmd prompt and anaconda powershell prompt to choose from.
