### ISSUE TITLE
Submitting mdx-net to the sound demixing challenge 2023

### ISSUE THREAD

**Issue by KimberleyJensen** [kuielab/mdx-net-submission#21]
Hello

Do you plan on submitting your mdx-net models to the sound demixing challenge 2023?

I have been trying to submit mine but they have changed the repository from the last mdx challenge.

If you submit your models please could you share your branch?

Here is the default one from aicrowd https://gitlab.aicrowd.com/aicrowd/challenges/sound-demixing-challenge-2023/sdx-2023-music-demixing-track-starter-kit/-/tree/master

Thanks :smiley:

**Comment by rlaalstjr47** [comment]
Here's the updated repository for this year's challenge
https://gitlab.aicrowd.com/kim_min_seok/kuielab-mdx-net_mdx23
