### ISSUE TITLE
How to use the Conv_TDF_net_trim class?

### ISSUE THREAD

**Issue by Logicino** [kuielab/mdx-net-submission#23]
Hello, I looked into the branch "Leaderboard_A" of this project 
I debugged it an I find out that in this branch, this only takes the imported "demucs" package to do the source separation
I find there is a `Conv_TDF_net_trim` class in the models.py, but the branch "Leaderboard_A" doesn't use it
I tried to take the `get_models` method to use the `Conv_TDF_net_trim` class, howver it get bug of

```
Traceback (most recent call last):
  File "/data/xyth/mdx-net-submission/evaluator/music_demixing.py", line 148, in run
    self.evaluation()
  File "/data/xyth/mdx-net-submission/evaluator/music_demixing.py", line 124, in evaluation
    self.prediction_setup()
  File "/data/xyth/mdx-net-submission/predict_blend.py", line 22, in prediction_setup
    self.models = get_models(model_name, load=True, device=device)
  File "/data/xyth/mdx-net-submission/models.py", line 209, in get_models
    Conv_TDF_net_trim(
  File "/data/xyth/mdx-net-submission/models.py", line 129, in __init__
    model_name = model_name[:model_name.index('(')+1] + model_cfg + stft_cfg + model_name[model_name.index('(')+1:]
ValueError: substring not found
```

at the part of `models.py` (about 132 line)
```
            model_cfg = f'L{L}l{l}g{g}' 
            model_cfg += ', ' if (bn is None or bn==0) else f'bn{bn}, '

            stft_cfg = f'f{dim_f}t{dim_t}, '

            model_name = model_name[:model_name.index('(')+1] + model_cfg + stft_cfg + model_name[model_name.index('(')+1:]
            try:
                self.load_state_dict(
                    torch.load('{0}/{1}/{2}_lr{3}_e{4:05}.ckpt'.format(model_path, model_name, target_name, lr, epoch), map_location=device)
                )
                print(f'Loading model ({target_name})')
            except FileNotFoundError:
                print(f'Random init ({target_name})') 
```

Does the `Conv_TDF_net_trim` must be trained locally so it can work? Is there any existing checkpoints can be used? 
(I think the `bass.onnx`, `drums.onnx`, ... in the ONNX_A is for the model Demucs, not the  `Conv_TDF_net_trim` )
Thank you!

**Comment by Zokhoi** [comment]
From what I can see, this class is used in both the branches `leaderboard_A` and `leaderboard_B`. The models for demucs are `model/demucs.ckpt` and `model/demucs_extra.ckpt`, and the onnx models are for mdx-net.

If you want to remove any demucs output, you can set [this line](https://github.com/kuielab/mdx-net-submission/blob/leaderboard_A/predict_blend.py#L91) to
```py
b = np.array([[[1]], [[1]], [[1]], [[1]]])
```
and the script will not blend any demucs output into the results.

And if you want to train your own models, check [the original repo for that](https://github.com/kuielab/mdx-net), or the [mdx23 mdx-net starter kit](https://github.com/ws-choi/sdx23).

**Comment by Logicino** [comment]
> From what I can see, this class is used in both the branches `leaderboard_A` and `leaderboard_B`. The models for demucs are `model/demucs.ckpt` and `model/demucs_extra.ckpt`, and the onnx models are for mdx-net.
> 
> If you want to remove any demucs output, you can set [this line](https://github.com/kuielab/mdx-net-submission/blob/leaderboard_A/predict_blend.py#L91) to
> 
> ```python
> b = np.array([[[1]], [[1]], [[1]], [[1]]])
> ```
> 
> and the script will not blend any demucs output into the results.
> 
> And if you want to train your own models, check [the original repo for that](https://github.com/kuielab/mdx-net), or the [mdx23 mdx-net starter kit](https://github.com/ws-choi/sdx23).

Thank you for your answer! It solves all my doubts.
